#!/usr/bin/env bash

main() {
    charcount='0'
	test -z "$1" && prompt="Password: " || prompt="${1}: "
    reply=''
    while IFS='' read -n '1' -p "${prompt}" -r -s 'char'; do
        case "${char}" in
            # Handles NULL
            $'\000')
				break
            ;;
            # Handles BACKSPACE and DELETE
            $'\010'|$'\177')
				if (( charcount > 0 )); then
					prompt=$'\b \b'
					reply="${reply%?}"
					(( charcount-- ))
				else
					prompt=''
				fi
			;;
            *)
				prompt='*'
				reply+="${char}"
				(( charcount++ ))
            ;;
        esac
    done
    printf '\n' >&2
    printf '%s\n' "${reply}"
}

main "$@"
