#!/bin/sh

pwd=$(pwd)
cd || exit 1

echo "Init submodules..."
yadm submodule update --recursive --init

if type wsl.exe > /dev/null 2>&1; then
	echo "Copying wezterm config to windows..."
	wuser=$(powershell.exe "\$env:UserName" | sed -E 's,(\S+).*,\1,g')
	cp -rf ~/.config/wezterm/ "/mnt/c/Users/$wuser/.config"
fi

curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

sudo mkdir -p /root/.config
sudo mkdir -p /root/.local/share
sudo ln -s $HOME/.config/nvim/ /root/.config
sudo ln -s $HOME/.local/share/nvim/ /root/.local/share

cd "$pwd" || exit 1
