#!/usr/bin/env sh

pwd=$(pwd)
cd || exit 1

echo "Init submodules..."
yadm submodule update --recursive --init

if type wsl.exe > /dev/null 2>&1; then
	echo "Copying wezterm config to windows..."
	wuser=$(powershell.exe "\$env:UserName" | sed -E 's,(\S+).*,\1,g')
	cp -rf ~/.config/wezterm/ "/mnt/c/Users/$wuser/.config"
fi

if type fish 2>&1 >/dev/null; then
	fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
fi

if sudo echo -n ''; then
	sudo mkdir -p /root/.config
	sudo mkdir -p /root/.local/share
	sudo ln -s $HOME/.config/nvim/ /root/.config
	sudo ln -s $HOME/.local/share/nvim/ /root/.local/share
fi

cd "$pwd" || exit 1

if type fish 2>&1 >/dev/null; then
	echo to finish installing fish plugins run 'fisher install'
	echo to configure tide use: "tide configure --auto --style=Lean --prompt_colors='True color' --show_time='24-hour format' --lean_prompt_height='One line' --prompt_spacing=Compact --icons='Few icons' --transient=No"
fi
