[managers.system]
items = [
    "base",
    "base-devel",
    "bc",
    "curl",
    "flatpak",
    "git",
    "imagemagick",
    "inetutils",
    "iotop",
    "jq",
    "kdeconnect",
    "lib32-mesa-utils",
    "linux",
    "linux-firmware",
    "linux-headers",
    "lvm2",
    "man-db",
    "man-pages",
    "mesa-utils",
    "mtools",
    "neovim",
    "net-tools",
    "network-manager-applet",
    "networkmanager",
    "noto-fonts-emoji",
    "parallel",
    "partitionmanager",
    "pavucontrol",
    "polkit-gnome",
    "reflector",
    "sudo",
    "tmux",
    "wget",
    "yadm",
    "zsh",
]
