[managers.flatpak]
items = [
    "com.github.tchx84.Flatseal",
    "com.github.wwmm.easyeffects",
    "com.usebottles.bottles",
    "io.freetubeapp.FreeTube",
    "io.github.milkshiift.GoofCord",
    "io.gitlab.librewolf-community",
    "it.mijorus.gearlever",
    "net.audiorelay.AudioRelay",
    "org.gimp.GIMP",
    "org.kde.krita",
    "com.nextcloud.desktopclient.nextcloud",

    "com.heroicgameslauncher.hgl",
    "com.vysp3r.ProtonPlus",

    "com.obsproject.Studio",
    "io.github.flattool.Warehouse",
    "com.github.unrud.VideoDownloader",
    "io.gitlab.adhami3310.Impression",
    "io.gitlab.theevilskeleton.Upscaler",
    "io.missioncenter.MissionCenter",
    "org.blender.Blender",
    "org.gnome.Boxes",
    "org.gnome.eog",
    "org.inkscape.Inkscape",
]
