[managers.system]
items = [
    "webkit2gtk",
    "base-devel",
    "curl",
    "wget",
    "file",
    "openssl",
    "appmenu-gtk-module",
    "gtk3",
    "libappindicator-gtk3",
    "librsvg",
    "libvips",
]
