# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "automake",
    "bash",
    "bzip2",
    "cmake",
    "fish",
    "fzf",
    "gcc",
    "git",
    "gzip",
    "java-21-openjdk-headless",
    "jq",
    "make",
    "ncompress",
    "neovim",
    "nodejs",
    "ripgrep",
    "rustup",
    "sd",
    "tmux",
    "unzip",
    "wget",
    "zip",
    "zoxide",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

[managers.fisher]
items = [
    "ilancosman/tide@v6",
    "jorgebucaran/autopair.fish",
    "jorgebucaran/fisher",
    "nickeb96/puffer-fish",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    "cargo-update",
    "rebos",
]
