command_timeout = 50

format = """
$shell\
$all\
$fill\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$container\
$line_break\
$character\
"""

add_newline = false

[line_break]
disabled = false

[fill]
disabled = false
symbol = " "

[character]
success_symbol = "[❯](bold green)"

[time]
disabled = false
style = "dark-grey"
format = "[$time]($style)"

[container]
format = ' [$symbol \[$name\]]($style)'

[directory]
style = "bright-blue"
truncation_length = 10
truncate_to_repo = false
repo_root_style = "bold bright-blue"

[shell]
disabled = false
