command_timeout = 10

format = """
$all\
$fill\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$shell\
$container\
$line_break\
$character"""

add_newline = false

[line_break]
disabled = false

[fill]
disabled = false
symbol = " "

[character]
success_symbol = "[❯](#9134cc)"

[time]
disabled = false
style = "white"
format = "[$time]($style)"

[directory]
style = "bright-blue"
