#!/usr/bin/env bash

ENV_VARS=(
  __GL_SHADER_DISK_CACHE=1
  __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
  DXVK_HUD=compiler
)
DXVK_CONFIG=()
VKD3D_CONFIG=(
  force_host_cached
)
WINEDLLOVERRIDES=()
VKD3D_DISABLE_EXTENSIONS=()
GAMESCOPE_ARGS=()
ARGS_PRE=()
ARGS_POST=()

USE_GAMESCOPE=
USE_GAMEMODE=true
USE_MANGOHUD=true
USE_VKBASALT=

COMMAND_PRE=()
COMMAND_POST=()
