#!/usr/bin/env bash

ENV_VARS=(
  __GL_SHADER_DISK_CACHE=1
  __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
  DXVK_HUD=compiler
  # WINE_CPU_TOPOLOGY=12
)
DXVK_CONFIG=()
VKD3D_CONFIG=(
  force_host_cached
)
WINEDLLOVERRIDES=()
VKD3D_DISABLE_EXTENSIONS=()
GAMESCOPE_ARGS=(
  --backend sdl
)
GAMESCOPE_ENV_VARS=()
ARGS_PRE=()
ARGS_POST=()

ENABLE_HDR=
USE_GAMEMODE=true
USE_MANGOHUD=true
USE_VKBASALT=

USE_GAMESCOPE=
GAMESCOPE_AUTO_OUTPUT_SIZE=
GAMESCOPE_AUTO_NESTED_SIZE=

COMMAND_PRE=()
COMMAND_POST=()
