#!/usr/bin/env fish

set sleep_time "$argv[1]"
test -z "$sleep_time" && set sleep_time 1

sleep $sleep_time

if test -z "$WAYLAND_DISPLAY"
    xdotool type "$(xclip -o -selection clipboard)"
else
    ydotool type "$(wl-paste | sed -e 'y/|\'¿´+}ñ{-°!"&\/()=?¡¨*]Ñ[;:_/`-=[]\\\\;\'\/~!@^&*()_+{}|:"<>?/')"
end
