#!/usr/bin/env fish

set -l known g e w h m
set -l flags
set -l remove
set -l gs
set -l skip 0

for i in (seq (count $argv))
    if test $skip -gt 0
        set skip (math $skip - 1)
        continue
    end
    if echo -- $argv[$i] | rg -q -- '^-'
        if test "$argv[$i]" = --
            break
        end
        echo -- $argv[$i] | sd -- '^-' '' | string split '' | while read -l letter
            if contains $letter $known
                if test $letter = w -o $letter = h
                    set -a gs "-$letter" "$argv["$(math $i + 1)"]"
                    set -a remove (math $i + 1)
                    set skip 1
                else
                    set -a flags $letter
                end
                if not contains $i $remove
                    set -a remove $i
                end
            end
        end
    end
end

for i in (seq (count $remove) -1 1)
    set -e argv[$i]
end

set -l command $argv
set -l gamescope_flag

if contains g $flags; and type gamescope &>/dev/null
    set gamescope_flag yes

    set -l opt_flag
    if contains e $flags
        set -a opt_flag -e
    end

    set -l res (xrandr | rg -F '*+' | sd '^\s+|\s+$|\*\+' '' | sd '\s+|x' '\n')

    set -l prefix gamescope $opt_flag -W "$res[1]" -H "$res[2]" $gs -b -o 5 --backend=wayland --force-grab-cursor --adaptive-sync

    if contains m $flags; and type mangoapp &>/dev/null
        # set command MANGOHUD=0 "MANGOHUD_CONFIG=\"$(cat "$HOME/.config/MangoHud/MangoHud.conf" | rg '\S' | rg -v '^#|^legacy_layout|^pci_dev|,' | sd '\n' ',' | sd ',$' '')\"" $prefix --mangoapp $command
        set command env MANGOHUD=0 $prefix --mangoapp $command
    else
        set command $prefix $command
    end
end

if type gamemoderun &>/dev/null
    set command gamemoderun $command
end

if contains m $flags; and type mangohud &>/dev/null; and test -z "$gamescope_flag"
    set command env MANGOHUD=1 $command
end

if echo -- "$argv" | rg -qv '^\s*$'
    # printf '\'%s\' ' $command | sd ' $' '' >>~/.cache/game
    eval $(printf '\'%s\' ' $command)
else
    echo -- $command
end
