#!/bin/fish

if test (count $argv) -lt 3
    echo "usage: $(basename (status -f)) functions_file folder_to_search output_file <[ignore files...]>"
    return 1
end

set -l output "$argv[3]"
echo "begin;" >"$output"

cat $argv[1] | while read -l func
    set -l found (fd -i "^$func(_\d+)?\." "$argv[2]")

    if test -z "$found"
        echo "not found: $func" >&2
        continue
    end

    for file in $found
        if contains "$(basename "$file")" $argv[4..]
            echo "discarded: $file" >&2
        else
            echo (basename "$file")
            echo "" >>"$output"
            cat "$file" >>"$output"
        end
    end
end
