#!/bin/sh

if [ "$EUID" -eq 0 ]; then
	echo 'needs to be run as the user'
	return 1
else
	while [ true ]; do
		sleep 2
		sudo printf "" && break
	done
	sh -c 'while [ true ]; do sudo -v; sleep 60; done' &
fi

if type cmd.exe &> /dev/null; then
	cmd.exe /c "fedora config --default-user '$USER'" 2> /dev/null
fi

sudo dnf copr enable -y atim/starship
sudo dnf update -y
sudo dnf install -y git fish parallel tmux neovim gcc zlib-ng cmake zoxide ripgrep sd fd-find fzf starship
sudo dnf groupinstall -y "Development Tools" "Development Libraries"
sudo chsh -s $(which fish) "$USER"

mkdir -p "$HOME/.local/share" &> /dev/null
mkdir -p "$HOME/.local/bin" &> /dev/null
mkdir -p "$HOME/.config" &> /dev/null

git clone 'https://github.com/TheLocehiliosan/yadm.git' "/tmp/yadm"

if type cmd.exe &> /dev/null; then
	/tmp/yadm/yadm clone -b work 'https://github.com/DeadKper/dotfiles'
	/tmp/yadm/yadm submodule update --init --recursive
	/tmp/yadm/yadm pull --all --recurse-submodules
else
	/tmp/yadm/yadm clone 'git@github.com:DeadKper/dotfiles.git'
	/tmp/yadm/yadm submodule update --init --recursive
	/tmp/yadm/yadm pull --all --recurse-submodules

	git -C "$HOME/.config/nvim" remote set-url origin git@github.com:DeadKper/nvim.git
	git -C "$HOME/.config/nvim" checkout main
	git -C "$HOME/.config/nvim" pull

	sudo dnf install -y flatpak flatpak-kcm flatpak-libs flatpak-selinux flatpak-session-helper btop python3 pipx steam gamemode gamescope

	flatpak install --user -y com.bitwarden.desktop com.github.tchx84.Flatseal com.nextcloud.desktopclient.nextcloud com.usebottles.bottles io.freetubeapp.FreeTube io.github.fastrizwaan.WineZGUI io.github.flattool.Warehouse io.github.prateekmedia.appimagepool io.github.spacingbat3.webcord it.mijorus.gearlever md.obsidian.Obsidian net.agalwood.Motrix org.freedesktop.LinuxAudio.Plugins.TAP org.freedesktop.LinuxAudio.Plugins.swh org.freedesktop.Platform org.freedesktop.Platform.Compat.i386 org.freedesktop.Platform.GL.default org.freedesktop.Platform.GL32.default org.freedesktop.Platform.ffmpeg-full org.freedesktop.Platform.ffmpeg_full.i386 org.freedesktop.Platform.openh264 org.gimp.GIMP org.gnome.Platform org.gnome.Platform.Compat.i386 org.gtk.Gtk3theme.Breeze org.inkscape.Inkscape org.kde.Platform org.kde.kdenlive org.kde.krita org.kde.okular org.libreoffice.LibreOffice org.mozilla.firefox org.winehq.Wine.DLLs.dxvk org.winehq.Wine.gecko org.winehq.Wine.mono
	flatpak override --user --filesystem=xdg-data/icons:ro
	flatpak override com.usebottles.bottles --user --filesystem=xdg-data/applications
	flatpak override com.usebottles.bottles --user --filesystem=xdg-data/share/Steam
	flatpak override com.usebottles.bottles --user --filesystem=~/.var/app/com.valvesoftware.Steam/data/Steam
	flatpak override io.github.spacingbat3.webcord --user --filesystem=home:ro
	flatpak override org.mozilla.firefox --user --filesystem=xdg-data/icons
	flatpak override org.mozilla.firefox --user --filesystem=xdg-data/applications

	pipx install protonup
	newest=$(protonup --releases | tail -n 1)
	folder="$HOME/.local/share/Steam/compatibilitytools.d/GE-Latest-tmp"
	file="$folder/compatibilitytool.vdf"
	mkdir -p $folder
	echo '"compatibilitytools"' > "$file"
	echo '{' >> "$file"
	echo '  "compat_tools"' >> "$file"
	echo '  {' >> "$file"
	echo '    "GE-Latest" // Internal name of this tool' >> "$file"
	echo '    {' >> "$file"
	echo '      // - This manifest can be placed directly in compatibilitytools.d, in which case this should' >> "$file"
	echo "      //   be the relative or absolute path to the tool\'s dist directory." >> "$file"
	echo '      "install_path" "../'$newest'"' >> "$file"
	echo '' >> "$file"
	echo "      // For this template, we're going to substitute the display_name key in here, e.g.:" >> "$file"
	echo '      "display_name" "GE-Latest"' >> "$file"
	echo '' >> "$file"
	echo '      "from_oslist"  "windows"' >> "$file"
	echo '      "to_oslist"    "linux"' >> "$file"
	echo '    }' >> "$file"
	echo '  }' >> "$file"
	echo '}' >> "$file"
	protonup -t "$newest" -y

	if type kwriteconfig6 &> /dev/null; then
		kwriteconfig6 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true
	elif type kwriteconfig5 &> /dev/null; then
		kwriteconfig5 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true
	fi

	qdbus org.kde.KWin /KWin reconfigure
fi

ln -sr "$HOME/.local/share/yadm-project/yadm" "$HOME/.local/bin"

fish
