#!/usr/bin/env bash

path=$1
depth=$2
max_chars=$3

if test -z "$path"; then
    path="$PWD"
fi
if test -z "$depth"; then
    depth=5
fi
if test -z "$max_chars"; then
    max_chars=30
fi

if test "$path" = "$HOME"; then
    echo '~'
    exit 0
fi
if test "$path" = /; then
    echo /
    exit 0
fi

path="$(realpath -s "$path" 2>&1 | sed -E 's,realpath: (.+): No such file or directory,\1,g;s,'"'"'(.*)'"'"',\1,g')"

depth=$(bc <<< "$depth - 1")
out_path="$(basename "$path")"
path=$(dirname "$path")

while test "$depth" != 0 -a "$path" != / -a "$path" != "$HOME"; do
    depth=$(bc <<< "$depth - 1")
    out_path="$(basename "$path" | sed -E 's,^(\.?.).*,\1,g')/$out_path"
    path=$(dirname "$path")
done

# avoid shortening if only one folder up is left
if test "$(dirname "$path")" = / -o "$(dirname "$path")" = "$HOME"; then
    out_path="$(basename "$path" | sed -E 's,^(\.?.).*,\1,g')/$out_path"
    path=$(dirname "$path")
fi
out_path="$(echo $path | sed -E "s,^$HOME,~/," | sed -E "s,(~?/).+,\1…/,")$out_path"

if test "${#out_path}" -gt "$max_chars"; then
    echo "$(cut -c "1-$((max_chars-1))" <<< "$out_path")…"
else
    echo $out_path
fi
