#!/usr/bin/env bash

session="$(tmux display -p '#S')"

valid="^_popup_($(tmux list-sessions | rg -v '^_popup_' | sd '([^:]+).*' '$1' | sd '\n' '|' | sd '\|$' ''))$"

for orphan in $(tmux list-sessions | rg '^_popup_' | sd '([^:]+).*' '$1' | rg -v "$valid"); do
	tmux kill-session -t "$orphan"
done

if rg -q '_popup_' <<< "$session" && test "$(tmux list-sessions 2>/dev/null | wc -l)" -gt 1; then
	tmux switch-client -t $(tmux list-sessions | rg -v '^_popup_' | sd '([^:]+).*' '$1' | sort | head -1)
fi

exit 0
