#!/bin/bash

width=${2:-80%}
height=${2:-80%}
session=popup

if test -n "$(tmux has-session -t "$session" 2>&1)"; then
	tmux new -s $session -d
	sleep 0.2
	tmux send-keys -t "$session" "tmux set status-right ' #[fg=#e0e0e0]#{=17:#(\$HOME/.local/scripts/shortpath \"#{pane_current_path}\" \"3\")} ' && clear" Enter
fi

if test "$(tmux display-message -p -F "#{session_name}")" = "$session"; then
	tmux detach-client
else
	tmux popup -d '#{pane_current_path}' -xC -yC -w"$width" -h"$height" -E "tmux attach -t '$session'"
fi
