#!/usr/bin/env bash

session="_popup_$(tmux display -p '#S')"

if ! tmux has -t "$session" 2> /dev/null; then
	parent_session="$(tmux display -p '#{session_id}')"
	session_id="$(tmux new-session -dP -s "$session" -F '#{session_id}' -e TMUX_PARENT_SESSION="$parent_session" -c "$HOME")"
	tmux set -s -t "$session_id" key-table popup
	tmux set -s -t "$session_id" status off
	tmux set -s -t "$session_id" prefix None
	session="$session_id"
fi

tmux attach -t "$session" > /dev/null
