# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = ["flatpak", "cargo", "fisher"]

# Packages to be installed via the native package manager.
[managers.system]
items = [
	"7zip",
	"acl",
	"automake",
	"bash",
	"btop",
	"bzip2",
	"cmake",
	"distrobox",
	"fastfetch",
	"fd",
	"fish",
	"flatpak",
	"fuse",
	"fuse3",
	"fzf",
	"gamemode",
	"gamescope",
	"gcc",
	"git",
	"google-noto-sans-jp-fonts",
	"google-noto-sans-jp-mono-fonts",
	"goverlay",
	"gstreamer",
	"gstreamer-plugins-libav",
	"gstreamer-libnice",
	"gstreamer-plugin-openh264",
	"gstreamer-plugins-bad",
	"gstreamer-plugins-bad-codecs",
	"gstreamer-plugins-base",
	"gstreamer-plugins-good",
	"gstreamer-plugins-good-extra",
	"gstreamer-plugins-good-gtk",
	"gstreamer-plugins-libav",
	"gstreamer-plugins-ugly",
	"gstreamer-plugins-ugly-codecs",
	"gzip",
	"java-21-openjdk-headless",
	"jq",
	"kdeconnect-kde",
	"libopenssl-devel",
	"libreoffice",
	"libusb-0_1-4",
	"libusb-0_1-4-32bit",
	"make",
	"mangoapp",
	"mangohud",
	"mpv-devel",
	"ncompress",
	"neovim",
	"nodejs",
	"opensnitch",
	"opi",
	"qemu",
	"qt6-multimedia",
	"ripgrep",
	"rustup",
	"sd",
	"snapper",
	"snapper-zypp-plugin",
	"steam",
	"steamcmd",
	"tmux",
	"unrar",
	"unzip",
	"virt-manager",
	"wezterm",
	"wget",
	"wl-clipboard",
	"xclip",
	"xwayland",
	"xwaylandvideobridge",
	"yadm",
	"ydotool",
	"zip",
	"zoxide",
]
