# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = ["flatpak-base", "flatpak"]

# Packages to be installed via the native package manager.
[managers.system]
items = [
	"7zip",
	"acl",
	"autokey-gtk",
	"btop",
	"distrobox",
	"fastfetch",
	"fd",
	"flatpak",
	"fuse",
	"fuse3",
	"gamemode",
	"gamescope",
	"google-noto-sans-jp-fonts",
	"google-noto-sans-jp-mono-fonts",
	"goverlay",
	"gstreamer",
	"gstreamer-plugin-openh264",
	"gstreamer-plugins-libav",
	"kdeconnect-kde",
	"klassy",
	"libopenssl-devel",
	"libreoffice",
	"libusb-0_1-4",
	"libusb-0_1-4-32bit",
	"mangoapp",
	"mangohud",
	"mpv-devel",
	"opensnitch",
	"opensnitch-ui",
	"opi",
	"qemu",
	"qt6-multimedia",
	"snapper",
	"snapper-zypp-plugin",
	"steam",
	"steamcmd",
	"trash-cli",
	"unrar",
	"virt-manager",
	"wallpaper-engine-kde-plugin",
	"wezterm",
	"wl-clipboard",
	"xclip",
	"xwayland",
	"xwaylandvideobridge",
	"yadm",
	"ydotool",
]

[managers.zypper-obs]
items = [
	"obs://home:Hoog",
	"obs://home:lighthomo",
	"obs://home:our-obo-ros",
	"obs://home:Simmphonie:python",
	"obs://home:paul4us",
]
