# fisher

add = "fish -c 'fisher install #:?'"
remove = "fish -c 'fisher remove #:?'"
upgrade = "fish -c 'fisher update'"

plural_name = "fish plugins"

hook_name = "fisher"

[config]
many_args = true
