# Flatpak

add = "flatpak install --user -y #:?"
remove = "flatpak uninstall --user -y #:?"
upgrade = "flatpak upgrade --user -y"

plural_name = "flatpaks"

hook_name = "flatpaks"

[config]
many_args = true
