# Flatpak

add = "flatpak --user install --assumeyes #:?"
remove = "flatpak --user uninstall --assumeyes #:?"
upgrade = "flatpak upgrade --assumeyes"

plural_name = "flatpaks"

hook_name = "flatpaks"

[config]
many_args = true
