# --------------------------- #
#    Manager Configuration    #
# --------------------------- #

# Make sure to enter the exact command you use as the normal user!
# That means including 'sudo' or 'doas' or whatever if the command needs it.
# Where you would put items, enter '#:?'.

# Example: add = "sudo apt install #:?"

add = "echo y | sudo zypper addrepo -cf #:? $(echo #:? | sed -E 's,obs://,,')" # Example: sudo apt install #:?
remove = "echo y | sudo zypper removerepo $(echo #:? | sed -E 's,obs://,,')" # Example: sudo apt remove #:?
sync = "echo y | sudo zypper refresh" # Example: sudo apt update

plural_name = "zypper obs repositories"

hook_name = "zypper_obs" # This is used in hooks. (Example: post_system_packages_add)

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_args = BOOL: Can you supply many items as an argument? Example: 'sudo apt install git vim wget'

[config]
many_args = false
