#!/usr/bin/env bash

if type dnf >/dev/null 2>&1; then
	sudo dnf autoremove
fi

if type flatpak >/dev/null 2>&1; then
	flatpak uninstall --unused
fi

if type zypper >/dev/null 2>&1; then
	readarray -t unneeded < <(zypper packages --unneeded | grep '^i ' | cut -d \| -f 3 | awk '{$1=$1;print}')
	if test -n "${unneeded}"; then
		sudo zypper remove "${unneeded[@]}"
	fi
fi

if type nix-env >/dev/null 2>&1; then
	nix-collect-garbage --delete-older-than 30d
fi
