#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
	batt_info=$(pmset -g batt)
	if ! grep -q 'InternalBattery' <<< "$batt_info"; then
		exit 0
	fi
	capacity=$(grep -oE '[0-9]+%' <<< "$batt_info" | tr -d '%')
	charging=$(grep -q 'AC attached' <<< "$batt_info" && echo 1 || echo 0)
else
	battery="/sys/class/power_supply/$(ls /sys/class/power_supply/ | rg -i bat | tail -1 2>/dev/null)"
	power="/sys/class/power_supply/$(ls /sys/class/power_supply/ | rg -i ac | tail -1 2>/dev/null)"

	if ! rg -q '/sys/class/power_supply/\S+' <<< $battery; then
		exit 0
	fi

	capacity=$(cat "$battery/capacity")
	charging=$(cat "$power/online")
fi

if test "$charging" = 1; then
	if test "$capacity" -lt 5; then
		symbol='󰢟'
	elif test "$capacity" -lt 15; then
		symbol='󰢜'
	elif test "$capacity" -lt 25; then
		symbol='󰂆'
	elif test "$capacity" -lt 35; then
		symbol='󰂇'
	elif test "$capacity" -lt 45; then
		symbol='󰂈'
	elif test "$capacity" -lt 55; then
		symbol='󰢝'
	elif test "$capacity" -lt 65; then
		symbol='󰂉'
	elif test "$capacity" -lt 75; then
		symbol='󰢞'
	elif test "$capacity" -lt 85; then
		symbol='󰂊'
	elif test "$capacity" -lt 95; then
		symbol='󰂋'
	else
		symbol='󰂅'
	fi
else
	if test "$capacity" -lt 5; then
		symbol='󰂎'
	elif test "$capacity" -lt 15; then
		symbol='󰁺'
	elif test "$capacity" -lt 25; then
		symbol='󰁻'
	elif test "$capacity" -lt 35; then
		symbol='󰁼'
	elif test "$capacity" -lt 45; then
		symbol='󰁽'
	elif test "$capacity" -lt 55; then
		symbol='󰁾'
	elif test "$capacity" -lt 65; then
		symbol='󰁿'
	elif test "$capacity" -lt 75; then
		symbol='󰂀'
	elif test "$capacity" -lt 85; then
		symbol='󰂁'
	elif test "$capacity" -lt 95; then
		symbol='󰂂'
	else
		symbol='󰁹'
	fi
fi

echo " $symbol $capacity%" "$@"
