#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
	top -l 2 -n 0 | grep 'CPU usage' | tail -1 | awk '{print $3}'
else
	awk '/^cpu / {u=$2+$4; t=$2+$4+$5; if (NR==1){u1=u; t1=t;} else printf("%6.2f%%\n",($2+$4-u1) * 100 / (t-t1)); }' \
		<(cat /proc/stat) <(sleep 1; cat /proc/stat)
fi
