#!/usr/bin/env bash
if [ "$(uname)" = "Darwin" ] && [ "${BASH_VERSINFO[0]:-0}" -lt 4 ]; then
	exec /opt/homebrew/bin/bash "$0" "$@"
fi

_tty=$(tmux display -p '#{pane_tty}')
. "$(dirname "$0")/ssh-context" "$_tty"

if $is_ssh; then
	# tmux "$@" -c "#{pane_current_path}" -P -F "#{pane_id}" "ssh $ssh_host"
	new_pane=$(tmux "$@" -c "#{pane_current_path}" -P -F "#{pane_id}")
	tmux send-keys -t "$new_pane" "ssh $ssh_host" Enter C-l
else
	tmux "$@" -c "#{pane_current_path}"
fi
tmux refresh-client -S
