#!/usr/bin/env bash

[[ -p /dev/stdin ]] && { mapfile -t; set -- "${MAPFILE[@]}" "$@"; }

if test -z "$2" -o "$2" -lt 1; then
	echo "usage: cuttxt <string> <size>"
	exit 1
fi

if test "$2" -eq 1; then
	if test "${#1}" -gt "$2"; then
		echo "…"
	else
		echo $1
	fi
else
	if test "${#1}" -gt "$2"; then
		echo "$(cut -c "1-$(($2-1))" <<< "$1")…"
	else
		echo $1
	fi
fi
