#!/usr/bin/env bash

[[ -p /dev/stdin ]] && { mapfile -t; set -- "${MAPFILE[@]}" "$@"; }

if test -z "$1" -o -z "$2" -o "$2" -lt 1; then
	echo "usage: cuttxt <string> <size>"
	exit 1
fi

text="$1"
size="$2"
div="$3"

if test -n "$div" -a "${#text}" -gt "$size"; then
	text="$(cut -d "$div" -f 1 <<< "$text")"
fi

if test "${#text}" -gt "$size"; then
	echo "$(cut -c "1-$(($size-1))" <<< "$text")…"
else
	echo "$text"
fi
