#!/usr/bin/env bash

if test -n "$1"; then
	pane_tty="$1"
else
	pane_tty=$(tmux display -p '#{pane_tty}')
fi

readarray -t pane_commands < <(ps -efH | grep -A 2 -E "\s+$(sed 's,^/dev/,,' <<< "$pane_tty")\s+")
readarray -t pane_commands < <(printf '%s\n' "${pane_commands[@]}" | cut -c $(printf '%s\n' "${pane_commands[@]}" | head -1 | grep -oE '^(\S+\s+){7}' | wc -c)-)
pane_command="${pane_commands[0]}"

for cmd in "${pane_commands[@]:1}"; do
	if ! grep -q '^\s' <<< "$cmd"; then
		break
	fi
	pane_command="$(sed -E 's/^\s+//' <<< "$cmd")"
done

get_hostname() {
	if grep -qwF 'ssh' <<< "$pane_command"; then
		ssh_host=$(printf '%s\n' $pane_command | grep -F '@' || printf '%s\n' $pane_command | tail -1)
		if grep -q 'cyberark\.cloud' <<< "$ssh_host"; then
			ssh -qG $ssh_host | awk '/^user / {print $2}' | awk -F@ '{print $4}' | sed -E 's/#\w+$//'
		elif grep -q 'coppel\.cloud' <<< "$ssh_host"; then
			ssh -qG $ssh_host | awk '/^hostname / {print $2}' | sed -E 's/#\w+$//'
		else
			ssh -G $ssh_host 2>/dev/null | awk '/^hostname / { print $2; exit }'
		fi
	else
		hostname
	fi
}

get_hostname | grep -v '^/' | grep '\S' || hostname
