#!/usr/bin/env bash

if test -n "$1"; then
	pane_tty="$1"
else
	pane_tty=$(tmux display -p '#{pane_tty}')
fi

readarray -t commands < <(ps -eH -o user:30,tty,cmd | grep -A 1000 -E "^\S+\s+$(sed 's,^/dev/,,' <<< "$pane_tty")\s")
cut=$(echo "${commands[0]}" | grep -oE '^(\S+\s+){2}' | wc -c)
tty_commands=("${commands[0]}")

for cmd in "${commands[@]:1}"; do
	if grep -qE "^.{$cut}\s" <<< "$cmd"; then
		tty_commands+=("$cmd")
	else
		break
	fi
done

get_hostname() {
	if cut -c "${cut}-" <<< "$cmd" <<< "${tty_commands[-1]}" | grep -qE "^\s*($(which ssh)|ssh)\s+"; then
		ssh_host=$(printf '%s\n' ${tty_commands[-1]} | grep -F '@' | head -1)
		test -n "$ssh_host" || ssh_host=$(echo ${tty_commands[-1]} | grep -oE -- '-- \S+')
		test -n "$ssh_host" || ssh_host=$(printf '%s\n' ${tty_commands[-1]} | tail -1)
		if grep -qwF 'cyberark.cloud' <<< "$ssh_host"; then
			hostname=$(ssh -qG $ssh_host | awk '/^user / {print $2}' | awk -F@ '{print $4}' | sed -E 's/#\w+$//')
		elif grep -qwF 'coppel.cloud' <<< "$ssh_host"; then
			hostname=$(ssh -qG $ssh_host | awk '/^hostname / {print $2}' | sed -E 's/#\w+$//')
		else
			hostname=$(ssh -qG $ssh_host | awk '/^hostname / { print $2; exit }')
		fi
	fi
	if test -z "$hostname"; then
		cat /etc/hostname
	else
		echo $hostname
	fi
}

get_hostname
