#!/usr/bin/env bash

socket="$HOME/.cache/tmux_popup.socket"
session="$(tmux display -p '#S')"

if ! tmux -S "$socket" has -t "$session" 2> /dev/null; then
        parent_session="$(tmux display -p '#{session_id}')"
        parent_path="$(tmux display -p '#{session_path}')"
        session_id="$(tmux -S "$socket" new-session -dP -s "$session" -F '#{session_id}' -e TMUX_PARENT_SESSION="$parent_session" -c "$parent_path")"
        tmux -S "$socket" set -s -t "$session_id" key-table popup
        tmux -S "$socket" set -s -t "$session_id" status off
        tmux -S "$socket" set -s -t "$session_id" prefix None
        tmux -S "$socket" unbind -t "$session_id" Escape
        session="$session_id"
fi

tmux -S "$socket" attach -t "$session" > /dev/null