#!/usr/bin/env bash

session="$(tmux display -p '#S')"

stmx() {
    tmux -S "${XDG_CACHE_HOME:-$HOME/.cache}/tmux_popup.socket" "$@"
}

if ! stmx has -t "$session" 2> /dev/null; then
    parent_session="$(tmux display -p '#{session_id}')"
    parent_path="$(tmux display -p '#{session_path}')"
    session="$(stmx -f <(grep -vwF 'tmux-plugins/tmux-resurrect' ~/.config/tmux/tmux.conf | grep -vwF 'tmux-plugins/tmux-continuum') \
        new-session -dP -s "$session" -F '#{session_id}' -c "$parent_path" \
        -e TMUX_PARENT_SESSION="$parent_session" \
        -e fish_private_mode='yes' \
        -e HISTIGNORE='*')"
    stmx set -s -t "$session" key-table popup
    stmx set -s -t "$session" status off
    stmx set -s -t "$session" prefix None
    sleep 0.2
    stmx send "cd '$(tmux display -p '#{pane_current_path}')'; clear" Enter
fi

stmx attach -t "$session" > /dev/null
