#!/usr/bin/env bash

file="$(mktemp)"
trap "rm '$file' && trap - exit && exit 0" exit hup kill term int

{
	echo # remove current options
	while read -r line; do
		echo set -us $(awk '{print($1)}' <<< "$line")
	done <<< $(tmux list-keys | sed -E 's/^\S+\s+(-r\s)?\s*(-T)\s+(\S+)\s+(\S+).*/unbind \1\2 \3 \4/')
	while read -r line; do
		echo set -us $(awk '{print($1)}' <<< "$line")
	done <<< $(tmux show-options -s)
	while read -r line; do
		echo set -ug $(awk '{print($1)}' <<< "$line")
	done <<< $(tmux show-options -g)
	while read -r line; do
		echo set -ugw $(awk '{print($1)}' <<< "$line")
	done <<< $(tmux show-options -gw)

	echo # print default options
	tmux -L unconfigured -f /dev/null start-server \; list-keys
	while read -r line; do
		echo set -s $line
	done <<< $(tmux -L unconfigured -f /dev/null start-server \; show-options -s)
	while read -r line; do
		echo set -g $line
	done <<< $(tmux -L unconfigured -f /dev/null start-server \; show-options -g)
	while read -r line; do
		echo set -gw $line
	done <<< $(tmux -L unconfigured -f /dev/null start-server \; show-options -gw)
} > "$file"

tmux source "$file" 2>/dev/null
