#!/usr/bin/env bash

file="$(mktemp)"
trap "rm '$file' && trap - exit && exit 0" exit hup kill term int

{
	echo '# remove current options'
	tmux list-keys        | sed -E 's/^\S+\s+(-r\s)?\s*(-T)\s+(\S+)\s+(\S+).*/unbind \2 \3 \4/'
	tmux show-options -s  | awk '{print("set -us "$1)}'
	tmux show-options -g  | awk '{print("set -ug "$1)}'
	tmux show-options -gw | awk '{print("set -ugw "$1)}'

	echo '# set default options'
	tmux -L unconfigured -f /dev/null start-server \; list-keys
	tmux -L unconfigured -f /dev/null start-server \; show-options -s  | awk '{print("set -s "$N)}'
	tmux -L unconfigured -f /dev/null start-server \; show-options -g  | awk '{print("set -g "$N)}'
	tmux -L unconfigured -f /dev/null start-server \; show-options -gw | awk '{print("set -gw "$N)}'
} > "$file"

tmux source "$file" 2>/dev/null
