#!/usr/bin/env bash

seconds="$(cat /proc/uptime | cut -d ' ' -f 1 | sed 's/\..*//')"
hours="$((seconds/3600))"
minutes="$((seconds-hours*3600))"
minutes="$((minutes/60))"
echo "${hours}h ${minutes}m"
