#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
	boot_sec=$(sysctl -n kern.boottime | awk -F'[ ,]' '{print $4}')
	seconds=$(( $(date +%s) - boot_sec ))
else
	seconds="$(cat /proc/uptime | cut -d ' ' -f 1 | sed 's/\..*//')"
fi
hours="$((seconds/3600))"
minutes="$((seconds-hours*3600))"
minutes="$((minutes/60))"
echo "${hours}h ${minutes}m"
