#!/usr/bin/env bash

if test -n "$1"; then
	pane_tty="$1"
else
	pane_tty=$(tmux display -p '#{pane_tty}')
fi

readarray -t commands < <(ps -eH -o user:30,tty,cmd | grep -A 1000 -E "^\S+\s+$(sed 's,^/dev/,,' <<< "$pane_tty")\s")
cut=$(echo "${commands[0]}" | grep -oE '^(\S+\s+){2}' | wc -c)
tty_commands=("${commands[0]}")

for cmd in "${commands[@]:1}"; do
	if grep -qE "^.{$cut}\s" <<< "$cmd"; then
		tty_commands+=("$(sed -E 's/^\s+//' <<< "$cmd")")
	else
		break
	fi
done

get_username() {
	if cut -c "${cut}-" <<< "$cmd" <<< "${tty_commands[-1]}" | grep -qE '^\s*(/\S+/)?(ssh|sftp)\s+'; then
		ssh_host=$(printf '%s\n' ${tty_commands[-1]} | grep -F '@' | head -1 || printf '%s\n' ${tty_commands[-1]} | tail -1)
		if grep -qwE 'cyberark\.cloud|coppel\.cloud' <<< "$ssh_host"; then
			ssh -qG $ssh_host | awk '/^user / {print $2}' | awk -F@ '{print $3}'
		else
			ssh -qG $ssh_host 2>/dev/null | awk '/^user / {print $2}' | grep '\S' || ps -t $pane_tty -o user= | tail -1
		fi
	else
		echo "${tty_commands[-1]}" | awk '{print $1}'
	fi
}

get_username | grep -v '^/' | grep '\S' || echo $USER
